config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins

  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins #optional
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end

    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  #layout "admin" # informando o layout - por padrão o rails pega o application
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: %i[ new create edit update ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  private
    # método privado que vai ser usado no select (isso é para não chamarmos a model direto na view)
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Use retornos de chamada para compartilhar configurações ou restrições comuns entre ações.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Permitir apenas uma lista de parâmetros confiáveis.
    # o .permit funciona ocmo uma segurança maior para o app. Só teremosa acesso a esses dados.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:curso] = "Curso de ruby"
    session[:curso] = "Session salva"
    @nome = params[:nome]
    @sobrenome = params[:sobrenome]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def locale
    I18n.locale == :en ? "EUA" : "Português do Brasil"
  end

  def data_br(data_us)
    data_us.strftime("%d-%m-%Y")
  end

  def application_name
    "Crypto Wallet"
  end

  def get_environment
    if(Rails.env.development?)
      "Desenvolvimento"
    elsif(Rails.env.production)
      "Produção"
    else
      "Teste"
    end
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
  def coin_formatte
    "é isso ai"
  end
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <p>
    <strong><%= Coin.human_attribute_name(:description) %></strong>
    <%= coin.description %>
  </p>

  <p>
    <strong><%= Coin.human_attribute_name(:acronym)%></strong>
    <%= coin.acronym %>
  </p>

  <p class="image_coin">
    <strong><%= Coin.human_attribute_name(:url_image)%></strong>
    <%= image_tag coin.url_image, width: 25, height: 25 %>
  </p>

</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div class="form-edit-coin">
    <div>
      <%= form.label :url_image, style: "display: block" %>
      <%= form.text_field :url_image %>
    </div>
  </div>

  <div>
    <%= form.label :mining_type_id, style: "display: block" %>
    <%= form.select("mining_type_id", @mining_type_options, { include_blank: "Selecione..."}) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t('links.show'), @coin %> |
  <%= link_to t('links.back_to_coins'), coins_path %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= Coin.model_name.human(count: 2) %></h1>

<p><strong>Data:</strong> <%= data_br(Date.today) %></p>

<div id="coins">
  <% @coins.each do |coin| %>
    <%= render coin %>
    <p>
      <%= link_to t('links.show'), coin %>
    </p>
  <% end %>
</div>

<%= link_to "New coin", new_coin_path %>

<div>
  <small><%= application_name %></small>
</div>

app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t('links.back_to_coins'), coins_path %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
  <%# = @coin.id %>
  <%= link_to t('links.edit'), edit_coin_path(@coin) %> |
  <%= link_to t('links.back_to_coins'), coins_path %>

  <%= button_to t('links.destroy'), @coin, method: :delete %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h2>Header padrão - admin</h2>
    </header>
    <%= yield %>
    <footer>
      <h2>Footer padrão - admin</h2>
    </footer>
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag params[:controller], "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <%= javascript_include_tag params[:controller], "data-turbo-track" => "reload" %>
  </head>

  <body>
    <header>
      <h2>Header padrão</h2>
    </header>
    <h3><%= params[:controller]%></h3>
    <%= yield %>
    <footer>
      <h2>Footer padrão</h2>
    </footer>
  </body>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <p>
    <strong>Description:</strong>
    <%= mining_type.description %>
  </p>

  <p>
    <strong>Acronym:</strong>
    <%= mining_type.acronym %>
  </p>

</div>

app/views/mining_types/edit.html.erb
<h1>Editing mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Show this mining type", @mining_type %> |
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mining types</h1>

<div id="mining_types">
  <% @mining_types.each do |mining_type| %>
    <%= render mining_type %>
    <p>
      <%= link_to "Show this mining type", mining_type %>
    </p>
  <% end %>
</div>

<%= link_to "New mining type", new_mining_type_path %>

app/views/mining_types/new.html.erb
<h1>New mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>

<div>
  <%= link_to "Edit this mining type", edit_mining_type_path(@mining_type) %> |
  <%= link_to "Back to mining types", mining_types_path %>

  <%= button_to "Destroy this mining type", @mining_type, method: :delete %>
</div>

app/views/welcome/_menu.html.erb
<ul>
  <li><%= link_to "Moedas", coins_path %></li>
  <li><%= link_to "Tipo de mineração", mining_types_path %></li>
</ul>

app/views/welcome/index.html.erb
<h1>Seja Bem-vindo</h1>

<p><%= link_to 'Português', root_path(locale: 'pt-BR')%></p>
<p><%= link_to 'English', root_path(locale: 'en')%></p>

<p>O idioma padrão da aplicação é: <strong><%= t('actual_locale') %></strong></p>
<p><strong>Data: </strong><%= I18n.l(Date.today) %></p>

<p><%= cookies[:curso] %></p>
<p><%= session[:curso] %></p> 

<p>i18n: <%= I18n.t('hello')%></p>

<%= render "menu" %>

<p>Você está em ambiente de <strong><%= get_environment %></strong></p>
<p>Variável e instância/session <strong><%= @nome %></strong></p>
<p>Variável e instância/session só que com outro valor <strong><%= @sobrenome %></strong></p>